# You can use this to store API keys, mail server settings,
# or any other kind of configuration data that your application needs.
# In order to keep your production settings secret, store the production
# copy of this file on your server under shared/config/config.yml and copy
# it on deployment with this Capistrano task:#

# task :copy_config_files do
#   filename = "config/config.yml"
#   run "cp #{shared_path}/#{filename} #{release_path}/#{filename}"
# end
# after "deploy:update_code", :copy_config_files

encryption_key: someRandomBINARYKEY
mailer:
  server: mail.example.com
  username: someLOGIN
  password: s0meth1ngs3cr3t
vat: false
require_state_in_address: true

paperclip:
  s3_protocol: https
  s3_credentials:
    access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
    secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  path: ':class/:attachment/:style/:hash.:extension'
  bucket: <%= ENV['FOG_DIRECTORY'] %>
  hash_secret: f8c07cf79094ec06f77b6024b5d7936c79b5227274fb8e82c00blaha
payment_methods:
  -
    id: 1
    name: PayPal
    class_name: paypal
    description: AMEX, PayPal
    default: false
    currency_code: USD
    merchant_hosted_terminal: false
    gateway_mode: test # production or test for gateway and cim_gateway
    gateway:
      ip:         192.168.0.1
      login:      someLOGIN.yahoo.com
      password:   somePASSWORD
      signature:  someSIGNATURE
    cim_gateway:
      ip:         192.168.0.1
      login:      someLOGIN.yahoo.com
      password:   somePASSWORD
      signature:  someSIGNATURE
  -
    id: 2
    name: Netaxcept
    default: true
    description: VISA, MASTERCARD
    gateway_class_name: ActiveMerchant::Billing::NetaxeptGateway
    integration_class_name: ActiveMerchant::Billing::Integrations::Netaxept
    currency_code: NOK
    merchant_hosted_terminal: false
    gateway_mode: test # production or test for gateway and cim_gateway
    gateway:
      login: someLogin
      password: somePassword
    cim_gateway:
      login: someLogin
      password: somePassword
vat: true # TODO this should be available only for merchant country (main store command center)
require_state_in_address: true # TODO this should be requried only for some countries.
available_country:
  - PL
  - US
  - NOR
